import { Inter } from 'next/font/google'
import Navbar from '../components/Navbar';
import { Roboto } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

//importar estilos de letras
const roboto = Roboto({
  weight: ["300", "400", "500", "700"],
  styles: ["italic", "normal"],
  subsets: ["latin"]
})

export default function RootLayout({ children }) {
  return (
    <html>
      <body className='min-h-screen bg-slate-700'>
        <h1>JHSDh</h1>
     
        <Navbar />
        <h1>JHSDh</h1>
        {children}
        <h1>JHSDh</h1>

        </body>
    </html>
  )
}
